language: java
sudo: required
dist: bionic
jdk:
  - openjdk11

script: 
  - mvn deploy -Dhttps.protocols=TLSv1.2 --settings travis-settings.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
